### ISSUE TITLE
Some issues about the SUIM

### ISSUE THREAD

**Issue by YangEgp** [xahidbuffon/Awesome_Underwater_Datasets#1]
https://github.com/xahidbuffon/SUIM
I downloaded the SUIM dataset on your lab websites. I trained on traditional u-net (not the code you released). I know that about 83 images are different from the size of the mask. And I deleted these images. I process masks to make sure they are labeled correctly and can be entered into the network. eg: [255,255,255] - >[1,1,1]. To make sure these inputs are correct, I also check the pictures by visualizing these datasets. After that, I train it and set the input size(320,240) epoch 30, steps 5000 batch size 2. But I could not get the result as you mentioned in the paper. I got 10-20% fewer results than the different types of IOU in the paper.

After that, I trained on the code you released. And I found that the data loader is slow, in this case, I used logical operations to speed up the process. Here is my code.

```
def getSaliency(mask):
    # one combined category: HD/RO/FV/WR
        
    """
    RGB color code and object categories:
    ------------------------------------
    000 BW: Background waterbody
    001 HD: Human divers
    010 PF: Plants/sea-grass
    011 WR: Wrecks/ruins
    100 RO: Robots/instruments
    101 RI: Reefs and invertebrates
    110 FV: Fish and vertebrates
    111 SR: Sand/sea-floor (& rocks)
    """
    imw, imh = mask.shape[0], mask.shape[1]
    sal = np.zeros((imw, imh))
    # bkg = np.zeros((imw,imh))
    a = np.logical_and(np.logical_and(np.logical_not(mask[:, :, 0]),np.logical_not(mask[:,:, 1])),mask[:, :, 2])
    sal[a] = 1
    a = np.logical_and(np.logical_and(np.logical_not(mask[:, :, 2]), np.logical_not(mask[:, :, 1])), mask[:, :, 0])
    sal[a] = 1
    a = np.logical_and(np.logical_and(mask[:,:,0],mask[:,:,1]),np.logical_not(mask[:,:,2]))
    sal[a] = 1
    a = np.logical_and(np.logical_and(mask[:, :, 1], mask[:, :, 2]), np.logical_not(mask[:, :, 0]))
    sal[a] = 1

    return np.expand_dims(sal, axis=-1) 

```
```

def getRobotFishHumanReefWrecks(mask):
    # for categories: HD, RO, FV, WR, RI
    imw, imh = mask.shape[0], mask.shape[1]
    mask = np.rint(mask)
    Human = np.zeros((imw, imh))
    Robot = np.zeros((imw, imh))
    Fish = np.zeros((imw, imh))
    Reef = np.zeros((imw, imh))
    Wreck = np.zeros((imw, imh))
    a = np.logical_and(np.logical_and(np.logical_not(mask[:, :, 0]),np.logical_not(mask[:,:, 1])),mask[:, :, 2])
    Human[a] = 1
    a = np.logical_and(np.logical_and(np.logical_not(mask[:, :, 2]), np.logical_not(mask[:, :, 1])), mask[:, :, 0])
    Robot[a] = 1
    a = np.logical_and(np.logical_and(mask[:,:,0],mask[:,:,1]),np.logical_not(mask[:,:,2]))
    Fish[a] = 1
    a = np.logical_and(np.logical_and(mask[:, :, 0], mask[:, :, 2]), np.logical_not(mask[:, :, 1]))
    Reef[a] = 1
    a = np.logical_and(np.logical_and(mask[:, :, 1], mask[:, :, 2]), np.logical_not(mask[:, :, 0]))
    Wreck[a] = 1
    return np.stack((Robot, Fish, Human, Reef, Wreck), -1) 


```
However, I did not get the same size model as you released on google drive. After I check on the Internet, I change
save_weights_only = True 
to
save_weights_only = False
But my model is still 2KB smaller than yours. And the result I tested was still bad. I got 10-20% fewer results than the different types of IOU in the paper. To improve the result, I change the batch size from 2 to 32, but similarly, the result is still bad.

**Comment by mikurules** [comment]
I also found that about 83 images are different from the size of the mask. 
May I ask how to handle them correctly？

**Comment by FanYang991115** [comment]
> I also found that about 83 images are different from the size of the mask. May I ask how to handle them correctly？

The easiest way is to delete them when doing train and test.
![image](https://github.com/xahidbuffon/Awesome_Underwater_Datasets/assets/111620598/202cda79-af6e-464d-acbc-976dfee67471)
![image](https://github.com/xahidbuffon/Awesome_Underwater_Datasets/assets/111620598/b9fa4524-3213-4391-bd4d-baa64b43deaa)
